[package]
name = "holzpuzzle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
imageproc = "0.23.0"
image = "0.24.5"
rusttype = "0.9.3"
num = "0.4.1"
